- name: CloudEngine snmp location test
  hosts: cloudengine
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli

  tasks:

  - name: "Config SNMP location"
    ce_snmp_location:
      state:  present
      location:  nanjing China
      provider: "{{ cli }}"

  - name: "Undo SNMP location"
    ce_snmp_location:
      state:  absent
      location:  nanjing China
      provider: "{{ cli }}"