- name: CloudEngine snmp community test
  hosts: cloudengine
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli

  tasks:

  - name: "Config SNMP community"
    ce_snmp_community:
      state:  present
      community_name:  Wdz123456789
      access_right:  write
      provider: "{{ cli }}"

  - name: "Undo SNMP community"
    ce_snmp_community:
      state:  absent
      community_name:  Wdz123456789
      access_right:  write
      provider: "{{ cli }}"

  - name: "Config SNMP group"
    ce_snmp_community:
      state:  present
      group_name:  wdz_group
      security_level:  noAuthNoPriv
      acl_number:  2000
      provider: "{{ cli }}"

  - name: "Undo SNMP group"
    ce_snmp_community:
      state:  absent
      group_name:  wdz_group
      security_level:  noAuthNoPriv
      acl_number:  2000
      provider: "{{ cli }}"