- name: CloudEngine BGP neighbor address family test
  hosts: cloudengine
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli

  tasks:

  - name: "Config BGP peer Address_Family"
    ce_bgp_neighbor_af:
      state:  present
      vrf_name:  js
      af_type:  ipv4uni
      remote_address:  192.168.10.10
      nexthop_configure:  local
      provider: "{{ cli }}"

  - name: "Undo BGP peer Address_Family"
    ce_bgp_neighbor_af:
      state:  absent
      vrf_name:  js
      af_type:  ipv4uni
      remote_address:  192.168.10.10
      nexthop_configure:  local
      provider: "{{ cli }}"